---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: speed-vol
spec:
  capacity:
    storage: 1G
  accessModes:
   - ReadWriteMany
  storageClassName: speed
  hostPath:
    path: /tmp/speed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
spec:
  storageClassName: speed
  accessModes:
   - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512M
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slow-vol
spec:
  capacity:
    storage: 10G
  accessModes:
   - ReadWriteMany
  storageClassName: slow
  hostPath:
    path: /tmp/slow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prestashop-claim
spec:
  storageClassName: slow
  accessModes:
   - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2G
---
