apiVersion: v1
kind: Pod
metadata:
  name: meteo
  labels:
    app: meteo
spec:
  containers:
   - name: meteo-cont
     image: pockost/telegraf-cf-weather
     env:
      - name: INFLUXDB_PORT
        value: "8086"
      - name: INFLUXDB_NAME
        value: mydb
      - name: INFLUXDB_USER
        value: user
      - name: INFLUXDB_PASSWORD
        value: user
      - name: INFLUXDB_HOST
        value: 172.17.0.5
